### ISSUE TITLE
Quoted callout results in IndexError

### ISSUE THREAD

**Issue by marioortizmanero** [sondregronas/mkdocs-callouts#13]
I run into the following issue:

```
$ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
ERROR   -  Error reading page 'README.md': list index out of range
Traceback (most recent call last):
  File "/Users/marioortizmanero/src/mappingdocs/venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs/commands/build.py", line 171, in _populate_page
    page.markdown = config.plugins.on_page_markdown(
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs/plugins.py", line 575, in on_page_markdown
    return self.run_event('page_markdown', markdown, page=page, config=config, files=files)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs_callouts/plugin.py", line 30, in on_page_markdown
    return parser.parse(markdown)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs_callouts/utils.py", line 172, in parse
    return '\n'.join(self.convert_line(line) for line in markdown.split('\n'))
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs_callouts/utils.py", line 172, in <genexpr>
    return '\n'.join(self.convert_line(line) for line in markdown.split('\n'))
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs_callouts/utils.py", line 163, in convert_line
    return self._convert_block(line) or self._convert_content(line)
  File "/Users/marioortizmanero/.cache/venv/v/mappingdocs/xWo4mCzFO9EUq8g4EGJQKpTS6QA/lib/python3.10/site-packages/mkdocs_callouts/utils.py", line 131, in _convert_content
    while match.group(2).count('>') < self.indent_levels[-1]:
IndexError: list index out of range
```

when using the following markdown:

~~~
> ```markdown
> > [!NOTE]
> > This is something that's good to know about!
> ```
~~~

This used to work on v0.10.

**Comment by sondregronas** [comment]
Thanks for reporting this - I'll have this fixed asap.

Is the markdown you provided supposed to be part of a blockquote, or is it within a callout?

**Comment by marioortizmanero** [comment]
> Is the markdown you provided supposed to be part of a blockquote, or is it within a callout?

It was originally a workaround to include the source code of what a callout looks like on Markdown. As in, teaching others how to use callouts. Otherwise, this extension actually replaced the text _within the code snippet_. By putting it into a blockquote, the code snippet stayed the same. This seems to have been fixed in one of the version upgrades, so I can now just use:

~~~
```markdown
> [!NOTE]
> This is something that's good to know about!
```
~~~

Ideally, the original markdown should just be a block of code within a blockquote.

**Comment by sondregronas** [comment]
Doing that as a workaround makes perfect sense - but yeah it no longer messes with content within codefences, a bit of an oversight on my end.

Thanks for bringing this to my attention, it should be fixed in the latest release
